"""empty message

Revision ID: 1c730e33cd3c
Revises: 
Create Date: 2021-05-22 07:57:16.509166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c730e33cd3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=120), nullable=True),
    sa.Column('aanhef', sa.String(length=25), nullable=True),
    sa.Column('contributie', sa.Float(), nullable=True),
    sa.Column('pacht', sa.Float(), nullable=True),
    sa.Column('nr_tuinen', sa.Float(), nullable=True),
    sa.Column('borg', sa.Float(), nullable=True),
    sa.Column('ploegen', sa.Float(), nullable=True),
    sa.Column('roteren', sa.Float(), nullable=True),
    sa.Column('overig', sa.Float(), nullable=True),
    sa.Column('totaal', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nota')
    # ### end Alembic commands ###
